# Generated by Django 3.1 on 2020-08-12 14:45

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myCampId', models.CharField(max_length=20)),
                ('myProgId', models.CharField(max_length=10)),
                ('myAsetId', models.CharField(max_length=10)),
                ('myAsessionId', models.CharField(max_length=10)),
                ('mySemesterId', models.CharField(max_length=1)),
                ('myTheprogType', models.CharField(max_length=10)),
                ('myRemark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mydefault titile', max_length=100)),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2020, 8, 12, 14, 45, 2, 76041, tzinfo=utc), verbose_name='upload date')),
                ('scoresheetfile', models.FileField(upload_to='ScoresFolder/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
