# Generated by Django 3.1 on 2021-03-28 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GradeManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedscores',
            name='title',
            field=models.CharField(default='Mydefault title', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedscores',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 38, 6, 167067, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
